/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: Node_.idl
  Source: Node_.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_NODE__HPP
#define DDSCXX_NODE__HPP

#include "Float32MultiArray_.hpp"

#include <cstdint>
#include <vector>

namespace graph_msg
{
namespace msg
{
namespace dds_
{
class Node_
{
private:
 std::vector<uint16_t> node_name__;
 std::vector<float> node_position_x__;
 std::vector<float> node_position_y__;
 std::vector<float> node_position_z__;
 std::vector<float> node_yaw__;
 std::vector<uint16_t> node_attribute__;
 std::vector<uint16_t> undefined__;
 std::vector<uint16_t> node_state_2__;
 std::vector<uint16_t> node_state_3__;
 std::vector<::graph_msg::msg::dds_::Float32MultiArray_> node_state_list__;

public:
  Node_() = default;

  explicit Node_(
    const std::vector<uint16_t>& node_name_,
    const std::vector<float>& node_position_x_,
    const std::vector<float>& node_position_y_,
    const std::vector<float>& node_position_z_,
    const std::vector<float>& node_yaw_,
    const std::vector<uint16_t>& node_attribute_,
    const std::vector<uint16_t>& undefined_,
    const std::vector<uint16_t>& node_state_2_,
    const std::vector<uint16_t>& node_state_3_,
    const std::vector<::graph_msg::msg::dds_::Float32MultiArray_>& node_state_list_) :
    node_name__(node_name_),
    node_position_x__(node_position_x_),
    node_position_y__(node_position_y_),
    node_position_z__(node_position_z_),
    node_yaw__(node_yaw_),
    node_attribute__(node_attribute_),
    undefined__(undefined_),
    node_state_2__(node_state_2_),
    node_state_3__(node_state_3_),
    node_state_list__(node_state_list_) { }

  const std::vector<uint16_t>& node_name_() const { return this->node_name__; }
  std::vector<uint16_t>& node_name_() { return this->node_name__; }
  void node_name_(const std::vector<uint16_t>& _val_) { this->node_name__ = _val_; }
  void node_name_(std::vector<uint16_t>&& _val_) { this->node_name__ = _val_; }
  const std::vector<float>& node_position_x_() const { return this->node_position_x__; }
  std::vector<float>& node_position_x_() { return this->node_position_x__; }
  void node_position_x_(const std::vector<float>& _val_) { this->node_position_x__ = _val_; }
  void node_position_x_(std::vector<float>&& _val_) { this->node_position_x__ = _val_; }
  const std::vector<float>& node_position_y_() const { return this->node_position_y__; }
  std::vector<float>& node_position_y_() { return this->node_position_y__; }
  void node_position_y_(const std::vector<float>& _val_) { this->node_position_y__ = _val_; }
  void node_position_y_(std::vector<float>&& _val_) { this->node_position_y__ = _val_; }
  const std::vector<float>& node_position_z_() const { return this->node_position_z__; }
  std::vector<float>& node_position_z_() { return this->node_position_z__; }
  void node_position_z_(const std::vector<float>& _val_) { this->node_position_z__ = _val_; }
  void node_position_z_(std::vector<float>&& _val_) { this->node_position_z__ = _val_; }
  const std::vector<float>& node_yaw_() const { return this->node_yaw__; }
  std::vector<float>& node_yaw_() { return this->node_yaw__; }
  void node_yaw_(const std::vector<float>& _val_) { this->node_yaw__ = _val_; }
  void node_yaw_(std::vector<float>&& _val_) { this->node_yaw__ = _val_; }
  const std::vector<uint16_t>& node_attribute_() const { return this->node_attribute__; }
  std::vector<uint16_t>& node_attribute_() { return this->node_attribute__; }
  void node_attribute_(const std::vector<uint16_t>& _val_) { this->node_attribute__ = _val_; }
  void node_attribute_(std::vector<uint16_t>&& _val_) { this->node_attribute__ = _val_; }
  const std::vector<uint16_t>& undefined_() const { return this->undefined__; }
  std::vector<uint16_t>& undefined_() { return this->undefined__; }
  void undefined_(const std::vector<uint16_t>& _val_) { this->undefined__ = _val_; }
  void undefined_(std::vector<uint16_t>&& _val_) { this->undefined__ = _val_; }
  const std::vector<uint16_t>& node_state_2_() const { return this->node_state_2__; }
  std::vector<uint16_t>& node_state_2_() { return this->node_state_2__; }
  void node_state_2_(const std::vector<uint16_t>& _val_) { this->node_state_2__ = _val_; }
  void node_state_2_(std::vector<uint16_t>&& _val_) { this->node_state_2__ = _val_; }
  const std::vector<uint16_t>& node_state_3_() const { return this->node_state_3__; }
  std::vector<uint16_t>& node_state_3_() { return this->node_state_3__; }
  void node_state_3_(const std::vector<uint16_t>& _val_) { this->node_state_3__ = _val_; }
  void node_state_3_(std::vector<uint16_t>&& _val_) { this->node_state_3__ = _val_; }
  const std::vector<::graph_msg::msg::dds_::Float32MultiArray_>& node_state_list_() const { return this->node_state_list__; }
  std::vector<::graph_msg::msg::dds_::Float32MultiArray_>& node_state_list_() { return this->node_state_list__; }
  void node_state_list_(const std::vector<::graph_msg::msg::dds_::Float32MultiArray_>& _val_) { this->node_state_list__ = _val_; }
  void node_state_list_(std::vector<::graph_msg::msg::dds_::Float32MultiArray_>&& _val_) { this->node_state_list__ = _val_; }

  bool operator==(const Node_& _other) const
  {
    (void) _other;
    return node_name__ == _other.node_name__ &&
      node_position_x__ == _other.node_position_x__ &&
      node_position_y__ == _other.node_position_y__ &&
      node_position_z__ == _other.node_position_z__ &&
      node_yaw__ == _other.node_yaw__ &&
      node_attribute__ == _other.node_attribute__ &&
      undefined__ == _other.undefined__ &&
      node_state_2__ == _other.node_state_2__ &&
      node_state_3__ == _other.node_state_3__ &&
      node_state_list__ == _other.node_state_list__;
  }

  bool operator!=(const Node_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::graph_msg::msg::dds_::Node_>::getTypeName()
{
  return "graph_msg::msg::dds_::Node_";
}

template <> constexpr bool TopicTraits<::graph_msg::msg::dds_::Node_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::graph_msg::msg::dds_::Node_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::graph_msg::msg::dds_::Node_>::type_map_blob_sz() { return 1624; }
template<> constexpr unsigned int TopicTraits<::graph_msg::msg::dds_::Node_>::type_info_blob_sz() { return 244; }
template<> inline const uint8_t * TopicTraits<::graph_msg::msg::dds_::Node_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x13,  0x02,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0xf1,  0xc6,  0x00,  0xb0,  0x37,  0xde,  0x5d,  0x95, 
 0x71,  0x7d,  0xdc,  0x33,  0x5c,  0x07,  0xcc,  0x00,  0xea,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0xda,  0x00,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06, 
 0x44,  0x22,  0x9b,  0x79,  0x10,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0x0b,  0x26,  0xc2,  0x95,  0x10,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09,  0xc0,  0x07,  0xb5,  0xb3,  0x10,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09,  0x32,  0x7f,  0x0d,  0xda, 
 0x10,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09, 
 0x26,  0x9c,  0x09,  0x75,  0x10,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x06,  0xf8,  0xa8,  0x63,  0x8b,  0x10,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06,  0x28,  0xc7,  0x92,  0x9c,  0x10,  0x00,  0x00,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06,  0x4e,  0x22,  0x62,  0xbc, 
 0x10,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06, 
 0xdd,  0x4c,  0x41,  0xdd,  0x1e,  0x00,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf1, 
 0x01,  0x00,  0x00,  0xf1,  0xe8,  0x77,  0xf8,  0xfa,  0xae,  0xdc,  0xc9,  0x47,  0xe9,  0x3a,  0x65,  0x7f, 
 0x05,  0x23,  0x2a,  0x21,  0x37,  0x08,  0xf1,  0xe8,  0x77,  0xf8,  0xfa,  0xae,  0xdc,  0xc9,  0x47,  0xe9, 
 0x3a,  0x65,  0x7f,  0x05,  0x23,  0x00,  0x00,  0x00,  0x48,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x38,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x19,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0xf1,  0x1b,  0xf9,  0xae,  0x76,  0xc4, 
 0xb5,  0x1f,  0xa1,  0x81,  0x15,  0xe3,  0xd7,  0x10,  0x44,  0xd1,  0xa2,  0x03,  0x96,  0x00,  0x00,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09, 
 0x1f,  0xc8,  0xc0,  0x53,  0xf1,  0x1b,  0xf9,  0xae,  0x76,  0xc4,  0xb5,  0x1f,  0xa1,  0x81,  0x15,  0xe3, 
 0xd7,  0x10,  0x44,  0x00,  0x47,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x37,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x1e,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf1,  0x01,  0x00,  0x00,  0xf1,  0x24,  0x7a,  0x23,  0x10, 
 0x66,  0x66,  0x68,  0x1a,  0x8e,  0x0b,  0xfd,  0xdd,  0x15,  0x45,  0x7a,  0xe0,  0xb4,  0x74,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x14,  0x4c,  0xaa,  0x23,  0xf1, 
 0x24,  0x7a,  0x23,  0x10,  0x66,  0x66,  0x68,  0x1a,  0x8e,  0x0b,  0xfd,  0xdd,  0x15,  0x45,  0x00,  0x00, 
 0x43,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x33,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x0c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x70,  0x00,  0x8e,  0x72,  0x17,  0x22,  0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x4e,  0xec,  0xfb,  0x50,  0x00,  0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x3a,  0x74,  0xf1,  0x5f,  0x00,  0xba,  0x03,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0xf2,  0x15,  0x42,  0xf6,  0x24,  0xf8,  0xf6,  0x15,  0x15,  0x1e,  0xde,  0xbe,  0x27,  0x61,  0xee,  0x00, 
 0xbb,  0x01,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x24,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x1c,  0x00,  0x00,  0x00,  0x67,  0x72,  0x61,  0x70,  0x68,  0x5f,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x4e,  0x6f,  0x64,  0x65,  0x5f,  0x00, 
 0x8b,  0x01,  0x00,  0x00,  0x0a,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06,  0x0b,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65, 
 0x5f,  0x6e,  0x61,  0x6d,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09,  0x11,  0x00,  0x00,  0x00, 
 0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x70,  0x6f,  0x73,  0x69,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x78,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0x11,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x70,  0x6f,  0x73, 
 0x69,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x79,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x23,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09,  0x11,  0x00,  0x00,  0x00, 
 0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x70,  0x6f,  0x73,  0x69,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x7a,  0x5f, 
 0x00,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0x0a,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x79,  0x61,  0x77, 
 0x5f,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x06,  0x10,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x61,  0x74,  0x74, 
 0x72,  0x69,  0x62,  0x75,  0x74,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06,  0x0b,  0x00,  0x00,  0x00, 
 0x75,  0x6e,  0x64,  0x65,  0x66,  0x69,  0x6e,  0x65,  0x64,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x20,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x06, 
 0x0e,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x73,  0x74,  0x61,  0x74,  0x65,  0x5f,  0x32, 
 0x5f,  0x00,  0x00,  0x00,  0x20,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x06,  0x0e,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65,  0x5f,  0x73,  0x74,  0x61, 
 0x74,  0x65,  0x5f,  0x33,  0x5f,  0x00,  0x00,  0x00,  0x33,  0x00,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf2,  0x01,  0x00,  0x00,  0xf2,  0x90,  0xfa,  0x7b,  0x63,  0xdd,  0xc6,  0x09,  0xd6, 
 0x91,  0xa8,  0x50,  0x10,  0x5f,  0x2a,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00,  0x6e,  0x6f,  0x64,  0x65, 
 0x5f,  0x73,  0x74,  0x61,  0x74,  0x65,  0x5f,  0x6c,  0x69,  0x73,  0x74,  0x5f,  0x00,  0x00,  0x00,  0xf2, 
 0x90,  0xfa,  0x7b,  0x63,  0xdd,  0xc6,  0x09,  0xd6,  0x91,  0xa8,  0x50,  0x10,  0x5f,  0x2a,  0x00,  0x00, 
 0x8c,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x31,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x29,  0x00,  0x00,  0x00,  0x67,  0x72,  0x61,  0x70,  0x68,  0x5f,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x46,  0x6c,  0x6f,  0x61,  0x74,  0x33, 
 0x32,  0x4d,  0x75,  0x6c,  0x74,  0x69,  0x41,  0x72,  0x72,  0x61,  0x79,  0x5f,  0x00,  0x00,  0x00,  0x00, 
 0x4c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x26,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0xf2,  0xb9,  0x2e,  0x3b,  0x1f,  0xb0,  0x01,  0x0a,  0xaa,  0xe1,  0x3e,  0xde,  0x13,  0x4a, 
 0x21,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x6c,  0x61,  0x79,  0x6f,  0x75,  0x74,  0x5f,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x18,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3, 
 0x01,  0x00,  0x00,  0x09,  0x06,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61,  0x5f,  0x00,  0x00,  0x00, 
 0xf2,  0xb9,  0x2e,  0x3b,  0x1f,  0xb0,  0x01,  0x0a,  0xaa,  0xe1,  0x3e,  0xde,  0x13,  0x4a,  0x21,  0x00, 
 0x8b,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x30,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x28,  0x00,  0x00,  0x00,  0x67,  0x72,  0x61,  0x70,  0x68,  0x5f,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x4d,  0x75,  0x6c,  0x74,  0x69,  0x41, 
 0x72,  0x72,  0x61,  0x79,  0x4c,  0x61,  0x79,  0x6f,  0x75,  0x74,  0x5f,  0x00,  0x4f,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x27,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf2, 
 0x01,  0x00,  0x00,  0xf2,  0xc6,  0x70,  0x38,  0xfd,  0xa4,  0x0f,  0x25,  0xba,  0x21,  0xe8,  0x4b,  0x8e, 
 0x80,  0x0e,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x64,  0x69,  0x6d,  0x5f,  0x00,  0x00,  0x00,  0x00, 
 0x1b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x0d,  0x00,  0x00,  0x00, 
 0x64,  0x61,  0x74,  0x61,  0x5f,  0x6f,  0x66,  0x66,  0x73,  0x65,  0x74,  0x5f,  0x00,  0x00,  0x00,  0xf2, 
 0xc6,  0x70,  0x38,  0xfd,  0xa4,  0x0f,  0x25,  0xba,  0x21,  0xe8,  0x4b,  0x8e,  0x80,  0x0e,  0x00,  0x00, 
 0x92,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x33,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x2b,  0x00,  0x00,  0x00,  0x67,  0x72,  0x61,  0x70,  0x68,  0x5f,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x6d, 
 0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x4d,  0x75,  0x6c,  0x74,  0x69,  0x41, 
 0x72,  0x72,  0x61,  0x79,  0x44,  0x69,  0x6d,  0x65,  0x6e,  0x73,  0x69,  0x6f,  0x6e,  0x5f,  0x00,  0x00, 
 0x52,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x70,  0x00,  0x07,  0x00,  0x00,  0x00,  0x6c,  0x61,  0x62,  0x65,  0x6c,  0x5f,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00, 
 0x06,  0x00,  0x00,  0x00,  0x73,  0x69,  0x7a,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x08,  0x00,  0x00,  0x00,  0x73,  0x74,  0x72,  0x69, 
 0x64,  0x65,  0x5f,  0x00,  0x00,  0x00,  0x00,  0x00,  0x7c,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0xf2,  0x15,  0x42,  0xf6,  0x24,  0xf8,  0xf6,  0x15,  0x15,  0x1e,  0xde,  0xbe,  0x27,  0x61,  0xee,  0xf1, 
 0xc6,  0x00,  0xb0,  0x37,  0xde,  0x5d,  0x95,  0x71,  0x7d,  0xdc,  0x33,  0x5c,  0x07,  0xcc,  0xf2,  0x90, 
 0xfa,  0x7b,  0x63,  0xdd,  0xc6,  0x09,  0xd6,  0x91,  0xa8,  0x50,  0x10,  0x5f,  0x2a,  0xf1,  0xe8,  0x77, 
 0xf8,  0xfa,  0xae,  0xdc,  0xc9,  0x47,  0xe9,  0x3a,  0x65,  0x7f,  0x05,  0x23,  0xf2,  0xb9,  0x2e,  0x3b, 
 0x1f,  0xb0,  0x01,  0x0a,  0xaa,  0xe1,  0x3e,  0xde,  0x13,  0x4a,  0x21,  0xf1,  0x1b,  0xf9,  0xae,  0x76, 
 0xc4,  0xb5,  0x1f,  0xa1,  0x81,  0x15,  0xe3,  0xd7,  0x10,  0x44,  0xf2,  0xc6,  0x70,  0x38,  0xfd,  0xa4, 
 0x0f,  0x25,  0xba,  0x21,  0xe8,  0x4b,  0x8e,  0x80,  0x0e,  0xf1,  0x24,  0x7a,  0x23,  0x10,  0x66,  0x66, 
 0x68,  0x1a,  0x8e,  0x0b,  0xfd,  0xdd,  0x15,  0x45, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::graph_msg::msg::dds_::Node_>::type_info_blob() {
  static const uint8_t blob[] = {
 0xf0,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x70,  0x00,  0x00,  0x00,  0x6c,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xc6,  0x00,  0xb0,  0x37,  0xde,  0x5d,  0x95,  0x71,  0x7d,  0xdc,  0x33, 
 0x5c,  0x07,  0xcc,  0x00,  0xee,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x4c,  0x00,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0xe8,  0x77,  0xf8,  0xfa,  0xae,  0xdc,  0xc9, 
 0x47,  0xe9,  0x3a,  0x65,  0x7f,  0x05,  0x23,  0x00,  0x4c,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf1,  0x1b,  0xf9,  0xae,  0x76,  0xc4,  0xb5,  0x1f,  0xa1,  0x81,  0x15,  0xe3,  0xd7,  0x10,  0x44,  0x00, 
 0x4b,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf1,  0x24,  0x7a,  0x23,  0x10,  0x66,  0x66,  0x68, 
 0x1a,  0x8e,  0x0b,  0xfd,  0xdd,  0x15,  0x45,  0x00,  0x47,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40, 
 0x70,  0x00,  0x00,  0x00,  0x6c,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0x15,  0x42,  0xf6, 
 0x24,  0xf8,  0xf6,  0x15,  0x15,  0x1e,  0xde,  0xbe,  0x27,  0x61,  0xee,  0x00,  0xbf,  0x01,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x4c,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0x90,  0xfa,  0x7b,  0x63,  0xdd,  0xc6,  0x09,  0xd6,  0x91,  0xa8,  0x50,  0x10,  0x5f,  0x2a,  0x00, 
 0x90,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00,  0xf2,  0xb9,  0x2e,  0x3b,  0x1f,  0xb0,  0x01,  0x0a, 
 0xaa,  0xe1,  0x3e,  0xde,  0x13,  0x4a,  0x21,  0x00,  0x8f,  0x00,  0x00,  0x00,  0x14,  0x00,  0x00,  0x00, 
 0xf2,  0xc6,  0x70,  0x38,  0xfd,  0xa4,  0x0f,  0x25,  0xba,  0x21,  0xe8,  0x4b,  0x8e,  0x80,  0x0e,  0x00, 
 0x96,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::graph_msg::msg::dds_::Node_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::graph_msg::msg::dds_::Node_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::graph_msg::msg::dds_::Node_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::graph_msg::msg::dds_::Node_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::graph_msg::msg::dds_::Node_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_name_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_name_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_x_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_position_x_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_y_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_position_y_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_z_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_position_z_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_yaw_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_yaw_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_attribute_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_attribute_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.undefined_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.undefined_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_2_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_state_2_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_3_().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.node_state_3_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_list_().size());
      if (!write(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!write(streamer, instance.node_state_list_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::graph_msg::msg::dds_::Node_& instance, bool as_key) {
  auto &props = get_type_props<::graph_msg::msg::dds_::Node_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::graph_msg::msg::dds_::Node_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_name_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_name_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_name_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_x_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_position_x_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_position_x_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_y_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_position_y_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_position_y_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_z_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_position_z_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_position_z_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_yaw_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_yaw_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_yaw_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_attribute_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_attribute_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_attribute_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.undefined_().size());
      if (!read(streamer, se_1))
        return false;
      instance.undefined_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.undefined_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_2_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_state_2_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_state_2_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_3_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_state_3_().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.node_state_3_()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_list_().size());
      if (!read(streamer, se_1))
        return false;
      instance.node_state_list_().resize(se_1);
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!read(streamer, instance.node_state_list_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::graph_msg::msg::dds_::Node_& instance, bool as_key) {
  auto &props = get_type_props<::graph_msg::msg::dds_::Node_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::graph_msg::msg::dds_::Node_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_name_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_x_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_y_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_position_z_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_yaw_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_attribute_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.undefined_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_2_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_3_().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.node_state_list_().size());
      if (!move(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!move(streamer, instance.node_state_list_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::graph_msg::msg::dds_::Node_& instance, bool as_key) {
  auto &props = get_type_props<::graph_msg::msg::dds_::Node_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::graph_msg::msg::dds_::Node_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, uint16_t(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 9:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, false))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      for (uint32_t i_1 = 0; i_1 < se_1; i_1++) {
      if (!max(streamer, instance.node_state_list_()[i_1], prop))
        return false;
      }  //i_1
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::graph_msg::msg::dds_::Node_& instance, bool as_key) {
  auto &props = get_type_props<::graph_msg::msg::dds_::Node_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_NODE__HPP
